<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthService.DAL\AuthService.DAL.csproj" />
    <ProjectReference Include="..\AuthService.Shared\AuthService.Shared.csproj" />
    <ProjectReference Include="..\AppAuth.Utils\AppAuth.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MSA.Shared.DataTypes">
      <HintPath>..\..\..\GIT PROJECT\MSA.Shared\MSA.Shared.Utils\bin\Debug\netstandard2.1\MSA.Shared.DataTypes.dll</HintPath>
    </Reference>
    <Reference Include="MSA.Shared.Utils">
      <HintPath>..\..\..\GIT PROJECT\MSA.Shared\MSA.Shared.Utils\bin\Debug\netstandard2.1\MSA.Shared.Utils.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
