// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AuthService.DAL.Models;

public partial class AppAuthServiceContext : DbContext
{
    public AppAuthServiceContext(DbContextOptions<AppAuthServiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppObject> AppObjects { get; set; }

    public virtual DbSet<AppRole> AppRoles { get; set; }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<RefTokenTracking> RefTokenTrackings { get; set; }

    public virtual DbSet<RoleRight> RoleRights { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppObject>(entity =>
        {
            entity.HasIndex(e => new { e.Number, e.AppId }, "IX_AppObjects").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AppId).HasColumnName("AppID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_IsDeleted");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ObjectType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("View")
                .HasComment("View, Process (button), Data")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppObjects_ObjectType");

            entity.HasOne(d => d.App).WithMany(p => p.AppObjects)
                .HasForeignKey(d => d.AppId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AppObjects_Applications");
        });

        modelBuilder.Entity<AppRole>(entity =>
        {
            entity.HasIndex(e => new { e.Number, e.AppId }, "IX_AppRoles").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AppId).HasColumnName("AppID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasComment("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppRoles_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppRoles_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppRoles_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_AppRoles_IsDeleted");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasComment("'System'")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppRoles_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppRoles_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasIndex(e => e.UserName, "IX_AppUsers").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CardNum)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AppUsers_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_AppUsers_IsDeleted");
            entity.Property(e => e.Mobile)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Pwd)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("Hash Infomation");
            entity.Property(e => e.PwdKey)
                .HasMaxLength(100)
                .HasComment("Salt dung de sinh ra hash");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Application>(entity =>
        {
            entity.HasIndex(e => e.Number, "IX_Applications");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AppKey).HasMaxLength(250);
            entity.Property(e => e.Audience).HasMaxLength(250);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Applications_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Applications_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Applications_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Applications_IsDeleted");
            entity.Property(e => e.Issuer).HasMaxLength(250);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Applications_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Applications_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Company).WithMany(p => p.Applications)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Applications_Companies");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasIndex(e => e.RegKey, "IX_Companies").IsUnique();

            entity.HasIndex(e => e.Number, "IX_Companies_1").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AppKey).HasMaxLength(250);
            entity.Property(e => e.Audience).HasMaxLength(250);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Companies_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Companies_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Companies_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Companies_IsDeleted");
            entity.Property(e => e.Issuer).HasMaxLength(250);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Companies_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Companies_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Number)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RegKey)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RefTokenTracking>(entity =>
        {
            entity.ToTable("RefTokenTracking");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RefTokenTracking_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RefTokenTracking_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.IssuedAt).HasColumnType("datetime");
            entity.Property(e => e.JwtId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RefTokenTracking_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RefTokenTracking_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.ReplacedByTokenId).HasComment("ID c?a Refresh Token m?i du?c c?p");
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Hash c?a Refresh Token d? b?o m?t");
        });

        modelBuilder.Entity<RoleRight>(entity =>
        {
            entity.Property(e => e.AppObjectId).HasColumnName("AppObjectID");
            entity.Property(e => e.CanCreate).HasAnnotation("Relational:DefaultConstraintName", "DF_Rights_CanCreate");
            entity.Property(e => e.CanDelete).HasAnnotation("Relational:DefaultConstraintName", "DF_Rights_CanDelete");
            entity.Property(e => e.CanList).HasAnnotation("Relational:DefaultConstraintName", "DF_Rights_CanList");
            entity.Property(e => e.CanRead).HasAnnotation("Relational:DefaultConstraintName", "DF_Rights_CanRead");
            entity.Property(e => e.CanUpdate).HasAnnotation("Relational:DefaultConstraintName", "DF_Rights_CanUpdate");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RoleRights_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ERights_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RoleRights_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ERights_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.RoleId)
                .HasComment("Role Name")
                .HasColumnName("RoleID");

            entity.HasOne(d => d.AppObject).WithMany(p => p.RoleRights)
                .HasForeignKey(d => d.AppObjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleRights_AppObjects");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AppRoleId).HasColumnName("AppRoleID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
