// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class AppObject
{
    public int Id { get; set; }

    public int AppId { get; set; }

    public string Number { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// View, Process (button), Data
    /// </summary>
    public string ObjectType { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public virtual Application App { get; set; }

    public virtual ICollection<RoleRight> RoleRights { get; set; } = new List<RoleRight>();
}
