// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class AppRole
{
    public int Id { get; set; }

    public string Number { get; set; }

    public int AppId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    /// <summary>
    /// &apos;System&apos;
    /// </summary>
    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }
}
