// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class AppUser
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    /// <summary>
    /// Hash Infomation
    /// </summary>
    public string Pwd { get; set; }

    /// <summary>
    /// Salt dung de sinh ra hash
    /// </summary>
    public string PwdKey { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string CardNum { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }
}
