// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class Company
{
    public int Id { get; set; }

    public string Number { get; set; }

    public string RegKey { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public string AppKey { get; set; }

    public string Issuer { get; set; }

    public string Audience { get; set; }

    public int? Expire { get; set; }

    public int? RefExpire { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}
