// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class RefTokenTracking
{
    public Guid Id { get; set; }

    /// <summary>
    /// Hash c?a Refresh Token d? b?o m?t
    /// </summary>
    public string TokenHash { get; set; }

    public DateTime IssuedAt { get; set; }

    public DateTime ExpiredAt { get; set; }

    public bool IsRevoked { get; set; }

    public bool IsUsed { get; set; }

    public string JwtId { get; set; }

    public int UserId { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    /// <summary>
    /// ID c?a Refresh Token m?i du?c c?p
    /// </summary>
    public Guid? ReplacedByTokenId { get; set; }
}
