// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class RoleRight
{
    public int Id { get; set; }

    /// <summary>
    /// Role Name
    /// </summary>
    public int RoleId { get; set; }

    public int AppObjectId { get; set; }

    public bool CanList { get; set; }

    public bool CanCreate { get; set; }

    public bool CanRead { get; set; }

    public bool CanUpdate { get; set; }

    public bool CanDelete { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public virtual AppObject AppObject { get; set; }
}
