// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthService.DAL.Models;

public partial class UserRole
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int AppRoleId { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }
}
