<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthService.DAL\AuthService.DAL.csproj" />
    <ProjectReference Include="..\AuthService.Shared\AuthService.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MSA.Shared.Utils">
      <HintPath>..\..\..\GIT PROJECT\MSA.Shared\MSA.Shared.Utils\bin\Debug\netstandard2.1\MSA.Shared.Utils.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
